apiVersion: v1
kind: ReplicationController
metadata:
  name: zxbk-codis-proxy
  namespace: qiqi-china-zxbk-prod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zxbk-codis-proxy
    spec:
      containers:
      - name: zxbk-codis-proxy
        image: harbor.zxbike.cn/public/codis:3.2v1
        imagePullPolicy: IfNotPresent
        #command: ["/bin/sh", "-c","codis-proxy -l $(POD_NAME).log -c $(CODIS_PATH)/config/proxy.toml --host-admin $(POD_IP):11080 --host-proxy $(POD_IP):19000 --zookeeper $(ZK_ADDR) --product_name $(PRODUCT_NAME) --product_auth $(PRODUCT_AUTH) --session_auth $(SESSION_AUTH) --pidfile log/proxy.pid |while [ ! -f /codis/$(POD_NAME).log.* ];do sleep 1;done|tail -f /codis/$(POD_NAME).log.*"]
        command: ["/bin/sh", "-c","codis-proxy -l $(POD_NAME).log -c $(CODIS_PATH)/config/proxy.toml --host-admin $(POD_IP):11080 --host-proxy $(POD_IP):19000 --zookeeper $(ZK_ADDR) --product_name $(PRODUCT_NAME) --product_auth $(PRODUCT_AUTH) --session_auth $(SESSION_AUTH) --pidfile log/proxy.pid"]
        #args: ["-l","log/$(POD_NAME).log","-c","$(CODIS_PATH)/config/proxy.toml","--host-admin","$(POD_IP):11080","--host-proxy","$(POD_IP):19000","--zookeeper","$(ZK_ADDR)","--product_name","$(PRODUCT_NAME)","--product_auth","$(PRODUCT_AUTH)","--session_auth","$(SESSION_AUTH)","--pidfile","log/proxy.pid"]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "codis-admin --dashboard=${DASHBOARD_ADDR} --remove-proxy --addr=${POD_IP}:11080 1>/dev/null 2>&1"]
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZK_ADDR
          value: "zxbk-zookeeper-public:2181"
        - name: DASHBOARD_ADDR
          value: "zxbk-codis-dashboard:18080"
        - name: PRODUCT_NAME
          value: "zxbk-codis"
        - name: PRODUCT_AUTH
          value: "MTIzLmNvbQo"
        - name: SESSION_AUTH
          value: "123"
        ports:
        - containerPort: 11080
          name: proxy
        - containerPort: 19000
          name: admin
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
        livenessProbe: &healthcheck
          exec:
            command: ["/bin/sh", "-c","redis-cli -h $POD_IP -p 19000 -a $SESSION_AUTH ping"]
        readinessProbe:
          <<: *healthcheck